# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool: Azure AKS Self-hosted
    steps:
  #  - task: AzureCLI@2
  #    inputs:
  #      azureSubscription: 'Aqua BD ARM connection'
  #      scriptType: 'bash'
  #      scriptLocation: 'inlineScript'
  #      inlineScript: 'az acr build --image test:latest --registry aquamanasip . --no-push'

    - task: CmdLine@2
      inputs:
        script: |
          az login --service-principal -u $(user) -p $(secret) --tenant bc034cf3-566b-41ca-9f24-5dc49474b05e
          #cat task.yaml | az acr task create -n aquaScanner -r aquamanasip -f - -c /azp/_work/1/s
          az acr task create \
            --registry aquamanasip \
            --name aquaScanner \
            --context https://github.com/manasiprabhavalkar/devsecops-demo-trivy.git#master \
            --file task.yaml \
            --git-access-token $(GIT_PAT)
            --set aquaPassword=$(aqua_password)
          az acr task run --registry aquamanasip --name aquaScanner
          