name: iac-scan
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@0.0.22
        with:
          scan-type: 'config'
          hide-progress: false
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH,MEDIUM'
          format: 'table'
          exit-code: 1
